language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rk90229/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  rk90229/react-test  npm test

after_success:
  - docker build -t rk90229/multi-client ./client
  - docker build -t rk90229/multi-nginx ./nginx
  - docker build -t rk90229/multi-server ./server
  - docker build -t rk90229/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rk90229/multi-client
  - docker push rk90229/multi-nginx
  - docker push rk90229/multi-server
  - docker push rk90229/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: fib-app
  env: FibApp-env
  bucket_name: elasticbeanstalk-us-east-1-253154466461
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
